/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAiRouteImport } from './routes/admin-ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MeasureGuideRouteImport } from './routes/measure-guide'
import { Route as MeasurementPassportRouteImport } from './routes/measurement-passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TailorsRouteImport } from './routes/tailors'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known/assetlinks[.]json'
import { Route as AuthenticatedAiDesignsRouteImport } from './routes/_authenticated/ai-designs'
import { Route as AuthenticatedAiStudioRouteImport } from './routes/_authenticated/ai-studio'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBusinessReportRouteImport } from './routes/_authenticated/business-report'
import { Route as AuthenticatedConsultationsRouteImport } from './routes/_authenticated/consultations'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFestiveRouteImport } from './routes/_authenticated/festive'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedMomentsRouteImport } from './routes/_authenticated/moments'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedMyEarningsRouteImport } from './routes/_authenticated/my-earnings'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedUnmatchedPaymentsRouteImport } from './routes/_authenticated/unmatched-payments'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as BookHandleRouteImport } from './routes/book.$handle'
import { Route as DesignTokenRouteImport } from './routes/design.$token'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as PassportTokenRouteImport } from './routes/passport.$token'
import { Route as PassportClaimRouteImport } from './routes/passport.claim'
import { Route as PassportMeRouteImport } from './routes/passport.me'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as StyleTokenRouteImport } from './routes/style.$token'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as TailorsCitySlugRouteImport } from './routes/tailors.$citySlug'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedQuotationsQuoteIdRouteImport } from './routes/_authenticated/quotations.$quoteId'
import { Route as AdminStoresStoreIdRouteImport } from './routes/admin.stores.$storeId'
import { Route as ApiCronDigestRouteImport } from './routes/api/cron/digest'
import { Route as ApiInternalTransferAlertRouteImport } from './routes/api/internal/transfer-alert'
import { Route as FitcheckOrderIdClientIdRouteImport } from './routes/fitcheck.$orderId.$clientId'
import { Route as PassportShareTokenRouteImport } from './routes/passport.share.$token'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin-ai',
  path: '/admin-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasureGuideRoute = MeasureGuideRouteImport.update({
  id: '/measure-guide',
  path: '/measure-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementPassportRoute = MeasurementPassportRouteImport.update({
  id: '/measurement-passport',
  path: '/measurement-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorsRoute = TailorsRouteImport.update({
  id: '/tailors',
  path: '/tailors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAiDesignsRoute = AuthenticatedAiDesignsRouteImport.update({
  id: '/ai-designs',
  path: '/ai-designs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiStudioRoute = AuthenticatedAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessReportRoute =
  AuthenticatedBusinessReportRouteImport.update({
    id: '/business-report',
    path: '/business-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultationsRoute =
  AuthenticatedConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFestiveRoute = AuthenticatedFestiveRouteImport.update({
  id: '/festive',
  path: '/festive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsRoute = AuthenticatedMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyEarningsRoute = AuthenticatedMyEarningsRouteImport.update({
  id: '/my-earnings',
  path: '/my-earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnmatchedPaymentsRoute =
  AuthenticatedUnmatchedPaymentsRouteImport.update({
    id: '/unmatched-payments',
    path: '/unmatched-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHandleRoute = BookHandleRouteImport.update({
  id: '/book/$handle',
  path: '/book/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignTokenRoute = DesignTokenRouteImport.update({
  id: '/design/$token',
  path: '/design/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportTokenRoute = PassportTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => PassportRoute,
} as any)
const PassportClaimRoute = PassportClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => PassportRoute,
} as any)
const PassportMeRoute = PassportMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => PassportRoute,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleTokenRoute = StyleTokenRouteImport.update({
  id: '/style/$token',
  path: '/style/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorsCitySlugRoute = TailorsCitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => TailorsRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsQuoteIdRoute =
  AuthenticatedQuotationsQuoteIdRouteImport.update({
    id: '/$quoteId',
    path: '/$quoteId',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AdminStoresStoreIdRoute = AdminStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCronDigestRoute = ApiCronDigestRouteImport.update({
  id: '/api/cron/digest',
  path: '/api/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTransferAlertRoute =
  ApiInternalTransferAlertRouteImport.update({
    id: '/api/internal/transfer-alert',
    path: '/api/internal/transfer-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const FitcheckOrderIdClientIdRoute = FitcheckOrderIdClientIdRouteImport.update({
  id: '/fitcheck/$orderId/$clientId',
  path: '/fitcheck/$orderId/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportShareTokenRoute = PassportShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => PassportRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-ai': typeof AdminAiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom': typeof CustomRoute
  '/delete-account': typeof DeleteAccountRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/measurement-passport': typeof MeasurementPassportRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRouteWithChildren
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailors': typeof TailorsRouteWithChildren
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/ai-designs': typeof AuthenticatedAiDesignsRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-report': typeof AuthenticatedBusinessReportRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/festive': typeof AuthenticatedFestiveRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/more': typeof AuthenticatedMoreRoute
  '/my-earnings': typeof AuthenticatedMyEarningsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/unmatched-payments': typeof AuthenticatedUnmatchedPaymentsRoute
  '/a/$token': typeof ATokenRoute
  '/book/$handle': typeof BookHandleRoute
  '/design/$token': typeof DesignTokenRoute
  '/e/$token': typeof ETokenRoute
  '/f/$token': typeof FTokenRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/passport/$token': typeof PassportTokenRoute
  '/passport/claim': typeof PassportClaimRoute
  '/passport/me': typeof PassportMeRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/style/$token': typeof StyleTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tailors/$citySlug': typeof TailorsCitySlugRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quoteId': typeof AuthenticatedQuotationsQuoteIdRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/internal/transfer-alert': typeof ApiInternalTransferAlertRoute
  '/fitcheck/$orderId/$clientId': typeof FitcheckOrderIdClientIdRoute
  '/passport/share/$token': typeof PassportShareTokenRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-ai': typeof AdminAiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom': typeof CustomRoute
  '/delete-account': typeof DeleteAccountRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/measurement-passport': typeof MeasurementPassportRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRouteWithChildren
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailors': typeof TailorsRouteWithChildren
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/ai-designs': typeof AuthenticatedAiDesignsRoute
  '/ai-studio': typeof AuthenticatedAiStudioRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/business-report': typeof AuthenticatedBusinessReportRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/festive': typeof AuthenticatedFestiveRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/more': typeof AuthenticatedMoreRoute
  '/my-earnings': typeof AuthenticatedMyEarningsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/shop': typeof AuthenticatedShopRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/unmatched-payments': typeof AuthenticatedUnmatchedPaymentsRoute
  '/a/$token': typeof ATokenRoute
  '/book/$handle': typeof BookHandleRoute
  '/design/$token': typeof DesignTokenRoute
  '/e/$token': typeof ETokenRoute
  '/f/$token': typeof FTokenRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/passport/$token': typeof PassportTokenRoute
  '/passport/claim': typeof PassportClaimRoute
  '/passport/me': typeof PassportMeRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/style/$token': typeof StyleTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tailors/$citySlug': typeof TailorsCitySlugRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/quotations/$quoteId': typeof AuthenticatedQuotationsQuoteIdRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/internal/transfer-alert': typeof ApiInternalTransferAlertRoute
  '/fitcheck/$orderId/$clientId': typeof FitcheckOrderIdClientIdRoute
  '/passport/share/$token': typeof PassportShareTokenRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-ai': typeof AdminAiRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/custom': typeof CustomRoute
  '/delete-account': typeof DeleteAccountRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/measure-guide': typeof MeasureGuideRoute
  '/measurement-passport': typeof MeasurementPassportRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRouteWithChildren
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tailors': typeof TailorsRouteWithChildren
  '/terms': typeof TermsRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/_authenticated/ai-designs': typeof AuthenticatedAiDesignsRoute
  '/_authenticated/ai-studio': typeof AuthenticatedAiStudioRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/business-report': typeof AuthenticatedBusinessReportRoute
  '/_authenticated/consultations': typeof AuthenticatedConsultationsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/festive': typeof AuthenticatedFestiveRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/moments': typeof AuthenticatedMomentsRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/my-earnings': typeof AuthenticatedMyEarningsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/unmatched-payments': typeof AuthenticatedUnmatchedPaymentsRoute
  '/a/$token': typeof ATokenRoute
  '/book/$handle': typeof BookHandleRoute
  '/design/$token': typeof DesignTokenRoute
  '/e/$token': typeof ETokenRoute
  '/f/$token': typeof FTokenRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/passport/$token': typeof PassportTokenRoute
  '/passport/claim': typeof PassportClaimRoute
  '/passport/me': typeof PassportMeRoute
  '/q/$token': typeof QTokenRoute
  '/r/$token': typeof RTokenRoute
  '/style/$token': typeof StyleTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tailors/$citySlug': typeof TailorsCitySlugRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/quotations/$quoteId': typeof AuthenticatedQuotationsQuoteIdRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/cron/digest': typeof ApiCronDigestRoute
  '/api/internal/transfer-alert': typeof ApiInternalTransferAlertRoute
  '/fitcheck/$orderId/$clientId': typeof FitcheckOrderIdClientIdRoute
  '/passport/share/$token': typeof PassportShareTokenRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/about'
    | '/admin'
    | '/admin-ai'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/custom'
    | '/delete-account'
    | '/features'
    | '/import'
    | '/measure-guide'
    | '/measurement-passport'
    | '/onboarding'
    | '/passport'
    | '/portal'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/sitemap.xml'
    | '/tailors'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/ai-designs'
    | '/ai-studio'
    | '/billing'
    | '/business-report'
    | '/consultations'
    | '/contracts'
    | '/dashboard'
    | '/festive'
    | '/inventory'
    | '/moments'
    | '/more'
    | '/my-earnings'
    | '/payments'
    | '/payroll'
    | '/privacy'
    | '/quotations'
    | '/reports'
    | '/shop'
    | '/staff'
    | '/unmatched-payments'
    | '/a/$token'
    | '/book/$handle'
    | '/design/$token'
    | '/e/$token'
    | '/f/$token'
    | '/jobs/$slug'
    | '/join/$token'
    | '/passport/$token'
    | '/passport/claim'
    | '/passport/me'
    | '/q/$token'
    | '/r/$token'
    | '/style/$token'
    | '/t/$token'
    | '/tailors/$citySlug'
    | '/clients/$clientId'
    | '/events/$eventId'
    | '/orders/$orderId'
    | '/quotations/$quoteId'
    | '/admin/stores/$storeId'
    | '/api/cron/digest'
    | '/api/internal/transfer-alert'
    | '/fitcheck/$orderId/$clientId'
    | '/passport/share/$token'
    | '/clients/'
    | '/events/'
    | '/orders/'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/about'
    | '/admin'
    | '/admin-ai'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/custom'
    | '/delete-account'
    | '/features'
    | '/import'
    | '/measure-guide'
    | '/measurement-passport'
    | '/onboarding'
    | '/passport'
    | '/portal'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/sitemap.xml'
    | '/tailors'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/ai-designs'
    | '/ai-studio'
    | '/billing'
    | '/business-report'
    | '/consultations'
    | '/contracts'
    | '/dashboard'
    | '/festive'
    | '/inventory'
    | '/moments'
    | '/more'
    | '/my-earnings'
    | '/payments'
    | '/payroll'
    | '/privacy'
    | '/quotations'
    | '/reports'
    | '/shop'
    | '/staff'
    | '/unmatched-payments'
    | '/a/$token'
    | '/book/$handle'
    | '/design/$token'
    | '/e/$token'
    | '/f/$token'
    | '/jobs/$slug'
    | '/join/$token'
    | '/passport/$token'
    | '/passport/claim'
    | '/passport/me'
    | '/q/$token'
    | '/r/$token'
    | '/style/$token'
    | '/t/$token'
    | '/tailors/$citySlug'
    | '/clients/$clientId'
    | '/events/$eventId'
    | '/orders/$orderId'
    | '/quotations/$quoteId'
    | '/admin/stores/$storeId'
    | '/api/cron/digest'
    | '/api/internal/transfer-alert'
    | '/fitcheck/$orderId/$clientId'
    | '/passport/share/$token'
    | '/clients'
    | '/events'
    | '/orders'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$handle'
    | '/about'
    | '/admin'
    | '/admin-ai'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/custom'
    | '/delete-account'
    | '/features'
    | '/import'
    | '/measure-guide'
    | '/measurement-passport'
    | '/onboarding'
    | '/passport'
    | '/portal'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/sitemap.xml'
    | '/tailors'
    | '/terms'
    | '/.well-known/assetlinks.json'
    | '/_authenticated/ai-designs'
    | '/_authenticated/ai-studio'
    | '/_authenticated/billing'
    | '/_authenticated/business-report'
    | '/_authenticated/consultations'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/festive'
    | '/_authenticated/inventory'
    | '/_authenticated/moments'
    | '/_authenticated/more'
    | '/_authenticated/my-earnings'
    | '/_authenticated/payments'
    | '/_authenticated/payroll'
    | '/_authenticated/privacy'
    | '/_authenticated/quotations'
    | '/_authenticated/reports'
    | '/_authenticated/shop'
    | '/_authenticated/staff'
    | '/_authenticated/unmatched-payments'
    | '/a/$token'
    | '/book/$handle'
    | '/design/$token'
    | '/e/$token'
    | '/f/$token'
    | '/jobs/$slug'
    | '/join/$token'
    | '/passport/$token'
    | '/passport/claim'
    | '/passport/me'
    | '/q/$token'
    | '/r/$token'
    | '/style/$token'
    | '/t/$token'
    | '/tailors/$citySlug'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/quotations/$quoteId'
    | '/admin/stores/$storeId'
    | '/api/cron/digest'
    | '/api/internal/transfer-alert'
    | '/fitcheck/$orderId/$clientId'
    | '/passport/share/$token'
    | '/_authenticated/clients/'
    | '/_authenticated/events/'
    | '/_authenticated/orders/'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HandleRoute: typeof HandleRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminAiRoute: typeof AdminAiRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CustomRoute: typeof CustomRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  FeaturesRoute: typeof FeaturesRoute
  ImportRoute: typeof ImportRoute
  MeasureGuideRoute: typeof MeasureGuideRoute
  MeasurementPassportRoute: typeof MeasurementPassportRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRouteWithChildren
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TailorsRoute: typeof TailorsRouteWithChildren
  TermsRoute: typeof TermsRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  ATokenRoute: typeof ATokenRoute
  BookHandleRoute: typeof BookHandleRoute
  DesignTokenRoute: typeof DesignTokenRoute
  ETokenRoute: typeof ETokenRoute
  FTokenRoute: typeof FTokenRoute
  JobsSlugRoute: typeof JobsSlugRoute
  JoinTokenRoute: typeof JoinTokenRoute
  QTokenRoute: typeof QTokenRoute
  RTokenRoute: typeof RTokenRoute
  StyleTokenRoute: typeof StyleTokenRoute
  TTokenRoute: typeof TTokenRoute
  ApiCronDigestRoute: typeof ApiCronDigestRoute
  ApiInternalTransferAlertRoute: typeof ApiInternalTransferAlertRoute
  FitcheckOrderIdClientIdRoute: typeof FitcheckOrderIdClientIdRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai': {
      id: '/admin-ai'
      path: '/admin-ai'
      fullPath: '/admin-ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measure-guide': {
      id: '/measure-guide'
      path: '/measure-guide'
      fullPath: '/measure-guide'
      preLoaderRoute: typeof MeasureGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement-passport': {
      id: '/measurement-passport'
      path: '/measurement-passport'
      fullPath: '/measurement-passport'
      preLoaderRoute: typeof MeasurementPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailors': {
      id: '/tailors'
      path: '/tailors'
      fullPath: '/tailors'
      preLoaderRoute: typeof TailorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-designs': {
      id: '/_authenticated/ai-designs'
      path: '/ai-designs'
      fullPath: '/ai-designs'
      preLoaderRoute: typeof AuthenticatedAiDesignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-studio': {
      id: '/_authenticated/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AuthenticatedAiStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-report': {
      id: '/_authenticated/business-report'
      path: '/business-report'
      fullPath: '/business-report'
      preLoaderRoute: typeof AuthenticatedBusinessReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations': {
      id: '/_authenticated/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthenticatedConsultationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/festive': {
      id: '/_authenticated/festive'
      path: '/festive'
      fullPath: '/festive'
      preLoaderRoute: typeof AuthenticatedFestiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments': {
      id: '/_authenticated/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedMomentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-earnings': {
      id: '/_authenticated/my-earnings'
      path: '/my-earnings'
      fullPath: '/my-earnings'
      preLoaderRoute: typeof AuthenticatedMyEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unmatched-payments': {
      id: '/_authenticated/unmatched-payments'
      path: '/unmatched-payments'
      fullPath: '/unmatched-payments'
      preLoaderRoute: typeof AuthenticatedUnmatchedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$handle': {
      id: '/book/$handle'
      path: '/book/$handle'
      fullPath: '/book/$handle'
      preLoaderRoute: typeof BookHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$token': {
      id: '/design/$token'
      path: '/design/$token'
      fullPath: '/design/$token'
      preLoaderRoute: typeof DesignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$token': {
      id: '/passport/$token'
      path: '/$token'
      fullPath: '/passport/$token'
      preLoaderRoute: typeof PassportTokenRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/claim': {
      id: '/passport/claim'
      path: '/claim'
      fullPath: '/passport/claim'
      preLoaderRoute: typeof PassportClaimRouteImport
      parentRoute: typeof PassportRoute
    }
    '/passport/me': {
      id: '/passport/me'
      path: '/me'
      fullPath: '/passport/me'
      preLoaderRoute: typeof PassportMeRouteImport
      parentRoute: typeof PassportRoute
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style/$token': {
      id: '/style/$token'
      path: '/style/$token'
      fullPath: '/style/$token'
      preLoaderRoute: typeof StyleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailors/$citySlug': {
      id: '/tailors/$citySlug'
      path: '/$citySlug'
      fullPath: '/tailors/$citySlug'
      preLoaderRoute: typeof TailorsCitySlugRouteImport
      parentRoute: typeof TailorsRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$quoteId': {
      id: '/_authenticated/quotations/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotations/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuoteIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/admin/stores/$storeId': {
      id: '/admin/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminStoresStoreIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cron/digest': {
      id: '/api/cron/digest'
      path: '/api/cron/digest'
      fullPath: '/api/cron/digest'
      preLoaderRoute: typeof ApiCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/transfer-alert': {
      id: '/api/internal/transfer-alert'
      path: '/api/internal/transfer-alert'
      fullPath: '/api/internal/transfer-alert'
      preLoaderRoute: typeof ApiInternalTransferAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitcheck/$orderId/$clientId': {
      id: '/fitcheck/$orderId/$clientId'
      path: '/fitcheck/$orderId/$clientId'
      fullPath: '/fitcheck/$orderId/$clientId'
      preLoaderRoute: typeof FitcheckOrderIdClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/share/$token': {
      id: '/passport/share/$token'
      path: '/share/$token'
      fullPath: '/passport/share/$token'
      preLoaderRoute: typeof PassportShareTokenRouteImport
      parentRoute: typeof PassportRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsQuoteIdRoute: typeof AuthenticatedQuotationsQuoteIdRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsQuoteIdRoute: AuthenticatedQuotationsQuoteIdRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiDesignsRoute: typeof AuthenticatedAiDesignsRoute
  AuthenticatedAiStudioRoute: typeof AuthenticatedAiStudioRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBusinessReportRoute: typeof AuthenticatedBusinessReportRoute
  AuthenticatedConsultationsRoute: typeof AuthenticatedConsultationsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFestiveRoute: typeof AuthenticatedFestiveRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMomentsRoute: typeof AuthenticatedMomentsRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedMyEarningsRoute: typeof AuthenticatedMyEarningsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedUnmatchedPaymentsRoute: typeof AuthenticatedUnmatchedPaymentsRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiDesignsRoute: AuthenticatedAiDesignsRoute,
  AuthenticatedAiStudioRoute: AuthenticatedAiStudioRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBusinessReportRoute: AuthenticatedBusinessReportRoute,
  AuthenticatedConsultationsRoute: AuthenticatedConsultationsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFestiveRoute: AuthenticatedFestiveRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMomentsRoute: AuthenticatedMomentsRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedMyEarningsRoute: AuthenticatedMyEarningsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedUnmatchedPaymentsRoute: AuthenticatedUnmatchedPaymentsRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminStoresStoreIdRoute: typeof AdminStoresStoreIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStoresStoreIdRoute: AdminStoresStoreIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PassportRouteChildren {
  PassportTokenRoute: typeof PassportTokenRoute
  PassportClaimRoute: typeof PassportClaimRoute
  PassportMeRoute: typeof PassportMeRoute
  PassportShareTokenRoute: typeof PassportShareTokenRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportTokenRoute: PassportTokenRoute,
  PassportClaimRoute: PassportClaimRoute,
  PassportMeRoute: PassportMeRoute,
  PassportShareTokenRoute: PassportShareTokenRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

interface TailorsRouteChildren {
  TailorsCitySlugRoute: typeof TailorsCitySlugRoute
}

const TailorsRouteChildren: TailorsRouteChildren = {
  TailorsCitySlugRoute: TailorsCitySlugRoute,
}

const TailorsRouteWithChildren =
  TailorsRoute._addFileChildren(TailorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HandleRoute: HandleRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminAiRoute: AdminAiRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CustomRoute: CustomRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  FeaturesRoute: FeaturesRoute,
  ImportRoute: ImportRoute,
  MeasureGuideRoute: MeasureGuideRoute,
  MeasurementPassportRoute: MeasurementPassportRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRouteWithChildren,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TailorsRoute: TailorsRouteWithChildren,
  TermsRoute: TermsRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  ATokenRoute: ATokenRoute,
  BookHandleRoute: BookHandleRoute,
  DesignTokenRoute: DesignTokenRoute,
  ETokenRoute: ETokenRoute,
  FTokenRoute: FTokenRoute,
  JobsSlugRoute: JobsSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
  QTokenRoute: QTokenRoute,
  RTokenRoute: RTokenRoute,
  StyleTokenRoute: StyleTokenRoute,
  TTokenRoute: TTokenRoute,
  ApiCronDigestRoute: ApiCronDigestRoute,
  ApiInternalTransferAlertRoute: ApiInternalTransferAlertRoute,
  FitcheckOrderIdClientIdRoute: FitcheckOrderIdClientIdRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
